---
title: "Little Rock Youth Cycling"
author: |
  | _____________________________________ 
  |                            
  |                            
  | lryc.org
  | 
  | Mailing Address
  |
  | Little Rock Youth Cycling
  | PO BOX 12345                           
  | Little Rock, AR 72205                  
  |                                     
  | _____________________________________ 
date: |
  |             
  | Approved/Revised: April 18, 2024 
header-includes:
- \usepackage{caption}
- \pagenumbering{gobble}
- \usepackage{ragged2e}
- \usepackage{indentfirst}
output: 
  pdf_document:
    fig_caption: yes
    number_sections: no
indent: false
---

\centering
\raggedright
\newpage
\tableofcontents
\justify
\newpage
\pagenumbering{arabic}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Article 1 - Name 

The name of the organization shall be Little Rock Youth Cycling (referred to hereinafter as simply "Club") 

# Article 2 - Objectives and Purpose 

A. To promote youth cycling in the Little Rock area through; 

   1. Providing a means for Little Rock area youth who are members of local National Interscholastic Cycling Association (NICA) teams to engage in group cycling related activities all year. 
   
      + Cycling related activities may be trail maintenance, trail advocacy, group bicycle rides, and cycling related training with local coaches, members of the Club, professional cyclists, and/or professional trail builders. 
     
B. No commercial use can be made of the name or logo of Little Rock Youth Cycling. 

C. No member shall use the name or logo of Little Rock Youth Cycling to exploit personal views. 

D. No member shall use the roster of members for personal, commercial, or professional services. 

E. The Club is organized and operated as a non-profit Social Welfare organization with the Internal Revenue Service 501(c)(3). As such the primary purpose is to promote the general interest of cycling for Little Rock area youth relative to education, safety, competition, and recreation. 

F. If the Club holds an event(s) which the members of the general public are invited to participate in for a fee, the income from the general public, less a proportional share of the expenses which will not benefit members, will be allocated to the general funds of Little Rock Youth Cycling. 

# Article 3 - Dedication of Assets 

A. The properties and assets of the Club are irrevocably dedicated to the fulfillment of the aim of the Club set forth in Article 2. 

B. No part of the earnings, properties, or assets of this club, upon dissolution or otherwise, shall inure to the exclusive benefit of any private person, individual, member, or director of the Club except in the fulfillment of said aims. 

C. On liquidation or dissolution, all properties and assets shall be utilized in fulfillment of outstanding obligations. The balance of obligations outstanding for all properties and assets have been exhausted shall be distributed equally between the membership. The balance of properties and assets remaining shall be distributed to a non-profit organization, chosen by the Board, consistent with the Club's Objective and Purpose set forth in Article 2. 

# Article 4 - Membership 

A. Classes of membership 

   1. Individual Supporting 
     
   2. Individual Active 
     
B. Anyone interested in supporting youth cycling in the Little Rock area is eligible for membership 

   1. Upon acceptance by the Board by application, and 
     
   2. Payment of dues as set by the Board. 

C. Membership dues to be determined by the Board. 

D. Active Members of any class will be deemed an Active Member if the following conditions are met: 

   1. Current payment of any required dues to be determined by the Board; and 
     
   2. Documentation of at least twenty (20) hours of service per individual member in a calendar year which promotes the Club objectives and purposes through any of the following programs: 
     
      + Little Rock Youth Cycling trail maintenance days 
       
      + Volunteering at Little Rock Youth Cycling organized events; or 
       
      + volunteering at any other Little Rock Youth Cycling board-approved event, with independent submission and verification of service hours to the Board of Directors. 
       
E. A copy of the bylaws shall be available for inspection by any member at any meeting and on the LRYC website. 

# Article 5 - Dues 

A. Dues shall be paid annually on or before the member's anniversary date in the amounts set by the Board of Directors. 

B. All dues for prospective members shall be paid to the Club. 

# Article 6 - Termination of Membership 

A. Cause of termination; 

   1. Resignation of member; or 
     
   2. Failure to pay dues in the amount and within the amount and within the times set forth in Article 5. 
     
B. Procedure for expulsion for members; 

   1. Notice shall be sent via e-mail to the e-mail provided for the member in the membership application documentation and recorded by the Board of Directors. 
     
      + Reasons for expulsion should be stated within records of expulsion. 
       
      + Notice shall be sent at least seven (7) days prior to expulsion. 
       
   2. Member shall be given the opportunity to be heard via e-mail, written statement, or special meeting with the Board of Directors. 
   
      + A simple 2/3^rds^ majority (greater than 67%) vote from the Board of Directors can reverse expulsion after the member is heard. 
      
   3. Any person shall receive the pro-rata refund of dues paid from the date of the expulsion to the end of the dues period.
   
C. Procedure for expulsion for teams; 

   1. Notice shall be sent via e-mail to the e-mail provided for a representative chosen by the teams membership application documentation and recorded by the Board of Directors. 
     
      + Reasons for expulsion should be stated within records of expulsion. 
       
      + Notice shall be sent at least seven (7) days prior to expulsion. 
       
   2. Team representative shall be given the opportunity to be heard via e-mail, written statement, or special meeting with the Board of Directors. 
   
      + A simple 2/3^rds^ majority (greater than 67%) vote from the Board of Directors can reverse expulsion for the team after the team representative is heard. 
      
   3. Any person from the team shall receive the pro-rata refund of dues paid from the date of the expulsion to the end of the dues period.
      
# Article 7 - Meetings of Members 

A. Place of meetings 

   1. Any place designated by the Board of Directors

B. Frequency of meetings 

   1. Meetings to be held at least one (1) time per year, but not more than montly and with a maximum interval of two (2) months. 
   
C. Notice of meeting to members 

   1.  Notice of meetings of members shall be sent to the members e-mail address on file specifying place, date, time, location, and in case of special agenda items, nature of the business to be conducted 
   
D. Notice of certain agenda items

   1. If action on any of the following proposals, written notice or waiver of notice stating the general nature of the proposals shall be given, or any member action on such proposals is invalid: 
   
      + Removing a director and officer; 
    
      + Amending the bylaws or articles of incorporation; 
    
      + Approving a contract or transaction in which a director has material financial interest; 
    
      + Expulsion of member; 
    
      + Matters that the Board of Directors intends to present for action by the members.

# Article 8 - Election of Officers 

A. Nominations 

   1. Any member may place names in nomination, either in person at a meeting, by mail or e-mail one (1) month prior to annual meeting, provided each nominee is also an Active Member. 
   
B. Officers and Election 

   1. The elected officers shall be President, Vice-President, and Treasurer. 
   
   2. The election of officers shall be held at the annual meeting. A plurality of the vote of the members voting constitutes an election. 
   
   3. If there are no candidates to oppose current Board members, no election is necessary. 
   
   4. No mail-in ballots will be accepted. 
   
   5. In the event that one candidate is nominated for each office, the entire slate may be elected by a simple majority vote of the annual meeting of members. 
   
   6. The term of office will be one (1) year. 
   
   7. Installation of officers select shall take place during the period between the annual meeting and February 1. 
   
   8. Newly elected officers shall assume duties on January 1st of the following year. 
   
   9. A person must be an Active member of the club for one (1) year to be eligible for office. 
   
C. At-large Board Member positions shall be appointed by individual Little Rock area NICA teams with representation in the Club. 

   1. Each participating NICA team shall have one At-large Board position as chosen by the individual Little Rock area NICA team. 
   
      + Current teams include the Mt Saint Mary Academy Belles, Capitol City Cranks, Catholic High School for Boys Rockets, and Central High School Tigers.
      + Teams can be added with official representation for the Club on as needed basis by 2/3^rds^ majority vote from the Board of Directors.
   
   2. No elections are required for appointed At-large Board member positions selected by individual Little Rock area NICA teams. 

D. Duties of Officers 

   1. President 
   
      + Serves as chair of the Board of Directors; 
      + Presides at all meetings of members and of the Board of Directors; 
      + Appoints all committee chairpersons and makes all special assignments, subject to approval of the board; 
      + Has general supervision of all club activities; 
      + Executes club policy and acts as liaison to other organizations; and 
      + Designates an At-large Board Member to record meeting minutes as necessary. 
      
   2. Vice President 
   
      + To assist President in the activities of the club; 
      + To preside over meeting when President is unavailable to attend; and 
      + To act as Interim President when President is absent for extended period of time. 
      
   3. Treasurer 
   
      + Acts as chief financial officer of club; 
      + Receives all funds due to the club and pays club bills in accordance to the budget; 
      + Sets up savings and checking accounts that honor any of the following officer’s signatures: President, Vice President, or Treasurer; 
      + Maintains and controls all accounts of the club; 
      + Maintains the books of the club and presents them for audit to the Board at least seven (7) days prior to the expiration of term of office; 
      + Prepares an annual financial report and presents it to the board prior to the annual meeting; 
      + Presents a synopsis of the annual financial report to members at the annual meeting; 
      + Presents current financial reports at each annual meeting; and 
      + Acts as liaison with the club and insurance provider for any club events. 
      
   4. At-large Board Members 
   
      + Serves as Secretary in order to record meeting minutes at the behest of the President; 
      + Works together with other Officers and/or members to facilitate activities for members related to trail maintenance, cycling advocacy, or group cycling events as listed below; 
      + Schedules and notifies all members of all trail work days; 
      + Schedules and notifies all members of club related events; 
      + Responsible for securing sponsors for club event(s) if necessary; 
      + Maintains accurate records of event(s) expenses and provides a budget for event(s); 
      + Completes all paperwork for any governing body that sanctions the event(s); 
      + Organizes and Coordinates Club Rides; 
      + Uses the website as a tool to organize and track ride participation and history; and 
      + Serves as liaison between individuals and groups in communications about trails and riding opportunities. 
      
# Article 9 - Directors 

A. Number of Directors 

   1. All elected officers are members of the Board of Directors. 
   
   2. Each At-large Board Member under Article 8 are members of the Board of Directors. 
   
B. Powers 

   1. General Powers – Subject to the provision of these bylaws relating to action required to be approved by the members, the business and affairs of the club shall be managed, and all administrative powers shall be exercised by or under the direction of the Board of Directors. 
   
   2. Specific Powers – Without prejudice to these general powers, and subject to the same limitations, the directors shall have the power to: 
   
      + Select committees, and employees of the club; prescribe any duties for them that are consistent with these bylaws; 
      + Adopt, make, and use a club seal; prescribe the forma of club memberships, and alter the form of the seal and certificate; and 
      + Remove a director and officer, subject to the concurrence of two-thirds majority at a meeting of members. 
      
C. Vacancies 

   1. Vacancies occurring to the Board of Directors due to a death, resignation, or removal shall be filled by appointment of the President with the concurrence of the Board. Vacancy of the President’s office shall be filled by one of the members of the Board. No director may resign when the Club would be left without a duly elected director or directors in charge of its affairs. 
   
D. Place of Meetings 

   1. Regular meetings of the board may be held at any time. Any meeting, regular or special, may be held by conference call or electronically as long as all Board members can communicate. 
   
E. Regular meetings 

   1. Regular meetings of the Board can be held without notice. 
   
F. Special Meetings 

   1. Authority to Call – A special meeting may be called by any member of the Board of Directors. 
   
   2. Notice
   
      + Notice of the time and place of the meeting shall be by mail, phone, or email; and 
      + Notice must be given at least forty-eight (48) hours before any special meeting. 
   
G. Quorum 

   1. A majority of the authorized number of directors shall constitute a quorum for the transaction of business. 
   
H. Voting 

   1. Unless otherwise provided within these bylaws, decisions of the Board shall be made based upon a simple majority of those present. 
   
   2. Normal Business which can be reasonably considered as necessary to Club functions, with regards to trail maintenance and group events, that involve a purchase that is less than $200 can be performed at the discretion of any Board Member without the need for a vote from the Board of Directors. 
   
      + The Board Member making the purchase should be aware of monetary limitations of the Club and consider whether or not reimbursement is possible. 
      + In the event that the Club has less than $2,000, a full vote from the Board Members is required for any purchase of any amount. 
      
I. Fees and Compensations 

   1. Directors, officers, and members may not receive compensation for their services. Reimbursement of expenses is permitted upon approval of the complete board by a majority vote, as outlined in Article . 

# Article 10 - Indemnification of Directors, Officers, Employees, and other agents

A. Definitions – for the purpose of this article 

   1. “Agent” means any person who is or was a director or officer, employees, committee member, or any other agent of the club; 
   2. “Proceedings” means any threatened, pending, or completed action, whether civil, criminal, administrative, or investigative; and 
   3. “Expenses” includes, without limitation, all attorney’s fees, costs, and any other expenses incurred in establishing a right to indemnification under this article. 
   
B. Successful Defense by Agent 

   1. To the extent that an agent of this club had been successful on the merits of defense of any proceedings referred to in this article, or in the defense of any claim, issue, or matter therein, the agent shall be indemnified against expenses actual and reasonably incurred by the agent in connection with the claim. If an agent either settles any such claim or sustains a judgment rendered against him, then the provisions of 10-C through 10-E shall determine whether the agent is entitled to indemnification. 
   
C. Action Brought by Persons other than the Club 

   1. Subject to the required findings to be made pursuant to 10-E, below, this club shall indemnify any person who was or is a party to any proceedings by reason that such person is or was an agent of this club, for all expenses, judgments, fines, settlements, and other amounts actually and reasonably incurred in the proceeding. 
   
   2. Exceptions - The club shall not indemnify for: 
   
       + An action brought by, or on behalf of, this club, or by an officer, director, or person granted status by the Attorney General; 
       + An action brought by the Attorney General on the ground that the defendant director was or is engaging in self-dealing; or 
       + An action brought by the Attorney General for breach of duty relating to assets held by a charitable trust. 
       
D. Actions Brought By or On Behalf of the Club 

   1. Claims settled out of court. If any agent settles an action brought by this club, with or without court approval, the agent shall receive no indemnification for either amount paid pursuant to the terms of the settlement or any expenses incurred in defending against the proceedings. 
   
   2. Claims and suits awarded against the agent. This club shall indemnify any person who was or is a party to any action brought by this club by reason of the fact that the person is or was an agent of this club, for all expenses incurred in the defense of that action,provided that both of the following is met: 
   
       + The determination of good faith conduct required by 10-E, below, must be made in the manner provided for in that section; and 
       + Upon application, the court in which the action was brought must determine that in view of all circumstances of the case, the agent should be entitled to indemnity. If the agent is found to be so entitled, the court shall determine the appropriate expenses to be reimbursed. 
   
E. Determination of Agent’s Good Faith conduct. Indemnification granted to an agent in 10-C and 10-D, above is the condition on the following: 

   1. Requires standard of good conduct. The agent seeking reimbursement must be found, in the manner provided below, to have acted in good faith in a manner he believed to be best interest of this club, and with such care, including reasonable inquiry, as an ordinary prudent person in a like position would use in similar circumstances. The termination of any proceedings by judgment, order, settlement, conviction, or a plea of nolo contendere or its equivalent shall not itself create a presumption that the person did not act in good faith or in a manner which he reasonably believed to be in the best interest of this club or that he had reasonable cause or believe that his conduct was unlawful. 

   2. Manner of determination of good faith conduct. The determination that the agent did act in a manner complying with paragraph 10-E-1 above shall be made by: 
   
       + The Board of Directors by a majority vote of quorum consisting of directors who are not parties to the proceedings; or 
       + The affirmative vote of the majority at a meeting of the members; or 
       + The court in which the proceeding is or was pending. 
       
F. Limitations. No indemnification or advance shall be made under this article, except as provided in 10-B or 10-E-2c, in any circumstances when it appears that: 

   1. The indemnification or advance would be inconsistent with a provision of these bylaws, a resolution of the members, or an agreement in effect at the time of the accrual of the alleged cause of action asserted in the proceedings. 
   2. The indemnification would be inconsistent with any condition expressly imposed by the court in approving a settlement. 
   
G. Advance of Expenses – Expenses incurred in defending any proceeding may be advanced by this club before the final disposition of the proceeding on receipt of an undertaking by the agent to repay the amount of the advance, unless it is determined ultimately that the agent is entitled to be indemnified as authorized by this article. 

H. Contractual Rights of Non-directors and Non-officers – Nothing contained in this article shall affect any right to indemnification to which persons other than directors or officers of this club may be entitled by contract or otherwise. 

I. Insurance – The Board of Directors may authorize the purchase of insurance on behalf of any agent of this club against liability incurred by the agent arising out of the agent’s status as such, whether or not this club would have power to indemnify the agent against liability under the provision of this section.

# Article 11 - Records and Reports 

A. Inspection rights – Any member of the club may upon five (5) days prior to notice to the club’s secretary, inspect and copy: 

   1. Names and addresses of the members, and determine their voting rights. 
   
   2. The minutes of meeting members, meetings of Board of Directors, and of committees. 
   
   3. The bylaws as amended to date. 
   
B. Inspection by Directors – Every Director shall have the absolute right at any reasonable time to inspect all books, records, and documents of every kind and the physical properties of the club. This inspection by a director may be made in person or by an agent or attorney, and includes the right to copy and make extracts of documents. 

C. Annual report – The issuance of an annual report or other periodic reports by the Board of Directors shall be made at the discretion of the Board as they see appropriate. However, the treasurer shall provide to the Board if so requested and to those members who request in writing, within One Hundred and Twenty (120) days of the close of the fiscal year, a report containing the following information in reasonable detail: 

   1. The assets and liabilities of the club as of the end of the fiscal year; 
   
   2. The principal changes in assets and liabilities during the fiscal year; and 
   
   3. The revenue or receipts, and the expenses or disbursements of the Club during the fiscal year. 

# Article 12 - Amendments 

A. The bylaws may be amended at a scheduled meeting of members, or special meeting, by an affirmative vote of two-thirds of the members present and voting, providing that the proposed amendments shall have been presented in writing at one of the previous meeting of members and have appeared in one edition of the club newsletter or posted on club website one month in advance. Complete printed copies can be made available upon request of any proposed changes.
